### ISSUE TITLE
How to link android library?

### ISSUE THREAD

**Issue by realyukii** [HemanthJabalpuri/AndroidExplorer#5]
I use your build script as a guide to assemble android application package without gradle/android studio, it successfully build without prompting any error, however it throw an error on runtime:
```
--------- beginning of crash
12-28 17:19:24.498 13786 13786 E AndroidRuntime: FATAL EXCEPTION: main
12-28 17:19:24.498 13786 13786 E AndroidRuntime: Process: com.example.helloworld, PID: 13786
12-28 17:19:24.498 13786 13786 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.helloworld/com.example.hellowor
ld.main}: android.view.InflateException: Binary XML file line #2 in com.example.helloworld:layout/activity_main: Binary XML file line #2 in com.example.hellowo
rld:layout/activity_main: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7965)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-28 17:19:24.498 13786 13786 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
12-28 17:19:24.498 13786 13786 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2 in com.example.helloworld:layout/activity_ma
in: Binary XML file line #2 in com.example.helloworld:layout/activity_main: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
12-28 17:19:24.498 13786 13786 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2 in com.example.helloworld:layout/activity_ma
in: Error inflating class androidx.constraintlayout.widget.ConstraintLayout
12-28 17:19:24.498 13786 13786 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: androidx.constraintlayout.widget.ConstraintLayout
```

the reason of crash is pretty obvious, it can't resolve symbol `ConstraintLayout` that are used on the layout xml file, but I'm not sure how to fix this, I have tried link the `constraintlayout-2.2.0/classes.jar` library but it still throw an error after I rebuild it

if you're interested to check what's wrong, I create a [git repository](https://gitlab.com/reyuki/learn-android) that contain build script and needed file on there, thanks!

**Comment by realyukii** [comment]
move the issue to more appropriate place, [stackoverflow](https://stackoverflow.com/questions/79313685/how-to-use-aar-file-manually-and-properly).
